name: Build laravel docker image

on:
  push:
    branches:
      - laravel

jobs:
  build-laravel-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to aliyun container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.aliyun_cs_username }}
          password: ${{ secrets.aliyun_cs_password }}

      - name: Build and push
        uses: docker/build-push-action@v6.5.0
        with:
          platforms: linux/amd64
          push: true
          context: ./laravel/8.3
          tags: |
            registry.cn-hangzhou.aliyuncs.com/codesandbox/laravel:latest
